In [1]:
import random
import numpy as np
from scipy import stats
from scipy.stats import norm, kstest, chisquare, chi2

In [3]:
runs = 100

sam_size = 100000
sam_rg_low = 1 
sam_rg_hig = 100

cqt_k = 10
chiq_sig = 0.05

# Chi-Squared

In [41]:
sam_arr = np.empty(sam_size)
res_arr_chsq = np.empty([runs, 2])
res_arr_kolm = np.empty([runs, 2])

In [130]:
f_expt = np.empty(cqt_k)
for i in range(cqt_k):
    f_expt[i] = (sam_size / cqt_k)
print(f_expt)

[10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]


In [135]:
# Random Number Generator

for i in range(runs):
    random.seed()
    for j in range(sam_size):
        sam_arr[j] = random.randrange(sam_rg_low, sam_rg_hig)

    sam_cls_counts = np.empty(cqt_k)
    #print("Number of Clusters " + str(sam_cls_counts.size))
    
    counter = 0
    for k in range(0, cqt_k):
        tmp_arr = np.where(((sam_arr > (sam_rg_hig/cqt_k * k)) & (sam_arr <= (sam_rg_hig/cqt_k * (k+1)))), sam_arr, 0)
        tmp_arr = tmp_arr[tmp_arr!=0]
        sam_cls_counts[k] = tmp_arr.size
        counter = counter + sam_cls_counts[k]
        #print("from " + str((sam_rg_hig/cqt_k) * k).rjust(6, " ") + " to " + str(((sam_rg_hig/cqt_k) * (k+1))).rjust(6, " ") + " : " + str(sam_cls_counts[k]).rjust(8, " "))
        #print(tmp_arr)
    #print(f_expt)
    #print(sam_cls_counts)
    #print(counter)
    
    print(sam_cls_counts)
    print(f_expt)
    res_arr_chsq[i, :] = chisquare(f_obs=sam_cls_counts, f_exp=f_expt)
    cri_value = stats.chi2.ppf(1-0.05, df=(cqt_k-1))
    if res_arr_chsq[i, 1] > chiq_sig:
        print("Chi-Square Run # " + str(i).rjust(4, " ") + 
              "  ||  pvalue=" + str(round(res_arr_chsq[i, 1], 10)).rjust(13, " ") +
              " > " + str(chiq_sig) + " and thus NOT statstically significant")
    else:
        if res_arr_chsq[i, 0] > cri_value:
            print("Chi-Square Run # " + str(i).rjust(4, " ") + 
                  "  ||  pvalue=" + str(res_arr_chsq[i, 1]).rjust(13, " ") + 
                  "  ||  x²(calc)="+ str(round(res_arr_chsq[i, 0], 7)).rjust(7, " ") + " > "
                  " critical value: " + str(round(cri_value, 2)).rjust(3, " ") + 
                  " thus random number ARE NOT uniformly distributed")
        else:
            print("Chi-Square Run # " + str(i).rjust(4, " ") + 
                  "  ||  pvalue=" + str(res_arr_chsq[i, 1]).rjust(13, " ") + 
                  "  ||  x²(calc)="+ str(round(res_arr_chsq[i, 0], 7)).rjust(7, " ") + " > "
                  " critical value: " + str(round(cri_value, 2)).rjust(3, " ") + 
                  " thus random numbers ARE uniformly distributed")
    print("\n\n")

[10227. 10042. 10111. 10103. 10080. 10032. 10115. 10033. 10144.  9113.]
[10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
Chi-Square Run #    0  ||  pvalue=1.264660221848518e-15  ||  x²(calc)=90.5466 >  critical value: 16.92 thus random number ARE NOT uniformly distributed



[10120. 10022.  9966. 10082. 10161. 10059. 10122. 10101. 10134.  9233.]
[10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
Chi-Square Run #    1  ||  pvalue=3.204915400267566e-11  ||  x²(calc)=68.3496 >  critical value: 16.92 thus random number ARE NOT uniformly distributed



[10117. 10012. 10284.  9944. 10107. 10100. 10162. 10172. 10047.  9055.]
[10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000. 10000.]
Chi-Square Run #    2  ||  pvalue=5.954921755302749e-19  ||  x²(calc)=107.0136 >  critical value: 16.92 thus random number ARE NOT uniformly distributed



[10165.  9979. 10127. 10192. 10094. 10027. 10228. 10019. 10083.  9086.]
[10000. 10000. 10000. 10000. 1

In [132]:
f_obs = np.array([8, 8, 10, 9, 12, 8, 10, 14, 10, 11])
f_exp = np.array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

print(f_obs.size)
print(f_obs)
print(f_exp.size)
print(f_exp)

chisquare(f_obs=f_obs, f_exp=f_exp)

10
[ 8  8 10  9 12  8 10 14 10 11]
10
[10 10 10 10 10 10 10 10 10 10]


Power_divergenceResult(statistic=np.float64(3.4000000000000004), pvalue=np.float64(0.946307673764427))

In [133]:
f_obs = np.array([35, 52, 47, 71, 62, 33])
f_exp = np.array([50, 50, 50, 50, 50, 50])

print(f_obs.size)
print(f_obs)
print(f_exp.size)
print(f_exp)

print(chisquare(f_obs=f_obs, f_exp=f_exp))
print(stats.chi2.ppf(1-0.05, df=5))

6
[35 52 47 71 62 33]
6
[50 50 50 50 50 50]
Power_divergenceResult(statistic=np.float64(22.240000000000002), pvalue=np.float64(0.0004713500068363369))
11.070497693516351


In [134]:
f_obs = np.array([8, 6, 10, 7, 8, 11, 9])
f_exp = np.array([9, 8, 11, 8, 10, 7, 6])

print(f_obs.size)
print(f_obs)
print(f_exp.size)
print(f_exp)

chisquare(f_obs=f_obs, f_exp=f_exp)

print(stats.chi2.ppf(1-0.05, df=6))

7
[ 8  6 10  7  8 11  9]
7
[ 9  8 11  8 10  7  6]
12.591587243743977


# Kolmogorov-Smirnov 

In [9]:
# Generate a sample from a normal distribution
np.random.seed(42)
sample_size = 100
mean = 0
std_dev = 1
sample = np.random.normal(mean, std_dev, sample_size)
sample_2 = np.random.normal(loc=0.5, scale=1.5, size=50)

# Compute the Empirical Distribution Function (EDF)
def empirical_distribution_function(x, data):
    return np.sum(data <= x) / len(data)

edf_values = [empirical_distribution_function(x, sample) for x in sample]

# Define the Reference Distribution
reference_cdf = norm.cdf(sample)

### One-Sample test

In [17]:
# Calculate the Kolmogorov–Smirnov Statistic
ks_statistic, p_value = kstest(sample, 'norm')

# Comparing
alpha = 0.05
critical_value = 1.36  # This value can be obtained from the Kolmogorov-Smirnov table for a specific significance level

print("\nOne-sample KS Test:")
print("Kolmogorov-Smirnov Statistic:", ks_statistic)
print("P-value:", p_value)

if ks_statistic > critical_value or p_value < alpha:
    print("Reject the null hypothesis. The sample does not come from the specified distribution.")
else:
    print("Fail to reject the null hypothesis. The sample comes from the specified distribution.")


One-sample KS Test:
Kolmogorov-Smirnov Statistic: 0.10357070563896065
P-value: 0.21805553378516207
Fail to reject the null hypothesis. The sample comes from the specified distribution.


### Two-Sample test

In [22]:
ks_statistic_2, p_value_2 = stats.ks_2samp(sample, sample_2)

print("\nTwo-sample KS Test:")
print("Kolmogorov-Smirnov statistic:", ks_statistic_2)
print("P-value:", p_value_2)

if ks_statistic > critical_value or p_value_2 < alpha:
    print("Reject the null hypothesis. The samples do not come from the same distribution.")
else:
    print("Fail to reject the null hypothesis. The samples come from the same distribution.")


Two-sample KS Test:
Kolmogorov-Smirnov statistic: 0.31
P-value: 0.002895162515658937
Reject the null hypothesis. The samples do not come from the same distribution.
